#!/usr/bin/env ruby

require 'zeitwerk'
loader = Zeitwerk::Loader.new

loader.push_dir("#{__dir__}/models")
loader.push_dir("#{__dir__}/src")
loader.logger = method(:puts)
loader.setup

Extensions::ArrayExtension; Extensions::StringExtension;
Bots::Bot.new.start
